### PR TITLE
Skip property enumeration for primitive-like types.

### PR DESCRIPTION
**Pull request by gary-palmer**
i.e. don't display the "Chars" property of a string, display the string.

This came about after trying to pass a list of strings or ints.

Wasn't sure on what the column header should be though; so went with typename.  perhaps some functionality for overriding column headers next?

### CODE REVIEW

**Comment by mookid8000** [comment]
Super – thanks 👍 

It'll be out in v. 2.0.0 in a few minutes

**Comment by gary-palmer** [comment]
Great! thanks!

Achievement unlocked;
- [x] First Pull request

**Comment by gary-palmer** [comment]
By the way; thanks for opening up this project, its a superb util.

**Comment by mookid8000** [comment]
good to hear 😃

**Pull request merged**
